// Dog Passport: Mock Dogs Data
// From final-mock-data.md specification

import { Dog } from '../types';

export const mockDogs: Dog[] = [
  // PTSD Service Dogs
  {
    id: 'dog-001',
    userId: 'user-001',
    name: 'Max',
    breed: 'Golden Retriever',
    dateOfBirth: new Date('2019-03-15'),
    age: 6,
    weight: 68,
    weightUnit: 'lbs',
    sex: 'Male',
    color: 'Golden Yellow',
    photo: 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24',
    microchip: 'MC-123456789',
    isServiceDog: true,
    taskType: 'ptsd',
    taskDescription: 'Trained to assist with PTSD symptoms including grounding during flashbacks, interrupting anxiety attacks, providing deep pressure therapy, and creating personal space in crowded areas.',
    trainingCertification: '/docs/max-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/john-doe-signature.png',
    verificationStatus: 'blue',
    checkmarkStatus: 'blue',
    verificationDate: new Date('2024-02-10'),
    verifiedBy: 'Dr. Emily Chen, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: false,
      publicAccessCleared: true,
    },
    personality: 'Calm, gentle, highly focused. Excellent in crowded environments. Loves children.',
    specialNotes: 'Prefers bulkhead seating on flights. Bring collapsible water bowl. Sensitive to loud noises.',
    hypoallergenicRating: 'low',
    serviceDogId: 'SD-2024-001',
    favoriteActivities: ['Swimming', 'Fetch', 'Hiking'],
    dietaryRestrictions: ['Grain-free preferred'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Jane Doe',
      phone: '+1-555-123-9999',
      relationship: 'Spouse',
    },
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-11-18'),
  },
  {
    id: 'dog-005',
    userId: 'user-005',
    name: 'Rocky',
    breed: 'Belgian Malinois',
    dateOfBirth: new Date('2019-11-30'),
    age: 5,
    weight: 72,
    weightUnit: 'lbs',
    sex: 'Male',
    color: 'Fawn with Black Mask',
    photo: 'https://images.unsplash.com/photo-1568393691622-c7ba131d63b4',
    microchip: 'MC-456789012',
    isServiceDog: true,
    taskType: 'ptsd',
    taskDescription: 'Military veteran support dog trained for PTSD, nightmare interruption, crowd control, hypervigilance management, and cover/watch behaviors.',
    trainingCertification: '/docs/rocky-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/david-park-signature.png',
    verificationStatus: 'blue',
    checkmarkStatus: 'blue',
    verificationDate: new Date('2024-05-20'),
    verifiedBy: 'Dr. Maria Garcia, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: false,
      publicAccessCleared: true,
    },
    personality: 'Highly trained, vigilant, calm under pressure. Protective but non-aggressive.',
    specialNotes: 'Military working dog veteran. Prefers quiet boarding areas. Avoid crowded gates.',
    hypoallergenicRating: 'low',
    serviceDogId: 'SD-2024-005',
    favoriteActivities: ['Agility Training', 'Tracking', 'Running'],
    dietaryRestrictions: ['High protein diet'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Sarah Park',
      phone: '+1-555-567-9999',
      relationship: 'Partner',
    },
    createdAt: new Date('2024-04-12'),
    updatedAt: new Date('2024-11-18'),
  },
  
  // Medical Alert Dogs
  {
    id: 'dog-002',
    userId: 'user-002',
    name: 'Luna',
    breed: 'Standard Poodle',
    dateOfBirth: new Date('2020-05-12'),
    age: 4,
    weight: 55,
    weightUnit: 'lbs',
    sex: 'Female',
    color: 'White',
    photo: 'https://images.unsplash.com/photo-1508672019048-805c876b67e2',
    microchip: 'MC-875464922',
    isServiceDog: true,
    taskType: 'medical-alert',
    taskDescription: 'Trained to detect blood sugar changes 20-30 minutes before diabetic episodes. Also trained for seizure alert with 95% accuracy rate.',
    trainingCertification: '/docs/luna-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/sarah-johnson-signature.png',
    verificationStatus: 'blue',
    checkmarkStatus: 'blue',
    verificationDate: new Date('2024-04-15'),
    verifiedBy: 'Dr. Rachel Kim, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: true,
      publicAccessCleared: true,
    },
    personality: 'Energetic, very intuitive, loves children. Extremely food motivated.',
    specialNotes: 'Calms handler during medical episodes. Bring favorite plush toy for flights. Needs access to water frequently.',
    hypoallergenicRating: 'high',
    serviceDogId: 'SD-2024-002',
    favoriteActivities: ['Swimming', 'Obedience Training', 'Playing with Toys'],
    dietaryRestrictions: ['Low-fat diet'],
    knownAllergies: ['Chicken'],
    emergencyContact: {
      name: 'Mark Johnson',
      phone: '+1-555-234-9999',
      relationship: 'Father',
    },
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: 'dog-008',
    userId: 'user-008',
    name: 'Coco',
    breed: 'Cavalier King Charles Spaniel',
    dateOfBirth: new Date('2021-06-10'),
    age: 3,
    weight: 18,
    weightUnit: 'lbs',
    sex: 'Female',
    color: 'Blenheim',
    photo: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee',
    microchip: 'MC-789012345',
    isServiceDog: true,
    taskType: 'medical-alert',
    taskDescription: 'Trained to detect cardiac events and alert handler to irregular heart rhythms before episodes occur. Alerts 15-20 minutes in advance.',
    trainingCertification: '/docs/coco-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/amanda-lewis-signature.png',
    verificationStatus: 'blue',
    checkmarkStatus: 'blue',
    verificationDate: new Date('2024-01-15'),
    verifiedBy: 'Dr. Emily Chen, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: false,
      publicAccessCleared: true,
    },
    personality: 'Sweet, attentive, sensitive to handler emotions. Velcro dog.',
    specialNotes: 'Small breed, fits under airline seat. Bring soft carrier for flights. Needs frequent bathroom breaks.',
    hypoallergenicRating: 'low',
    serviceDogId: 'SD-2024-007',
    favoriteActivities: ['Cuddling', 'Short Walks', 'Lap Time'],
    dietaryRestrictions: ['Senior formula (due to heart condition)'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Tom Lewis',
      phone: '+1-555-890-9999',
      relationship: 'Husband',
    },
    createdAt: new Date('2023-12-10'),
    updatedAt: new Date('2024-11-16'),
  },
  {
    id: 'dog-010',
    userId: 'user-009',
    name: 'Sadie',
    breed: 'Border Collie',
    dateOfBirth: new Date('2020-10-05'),
    age: 4,
    weight: 45,
    weightUnit: 'lbs',
    sex: 'Spayed',
    color: 'Black & White',
    photo: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d',
    microchip: 'MC-901234567',
    isServiceDog: true,
    taskType: 'medical-alert',
    taskDescription: 'Trained to detect oncoming seizures 10-30 minutes before they occur and alert handler to find safe location. Also performs blocking behaviors.',
    trainingCertification: '/docs/sadie-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/lisa-thompson-signature.png',
    verificationStatus: 'green',
    checkmarkStatus: 'green',
    verificationDate: new Date('2024-07-22'),
    verifiedBy: 'Dr. James Wilson, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: false,
      publicAccessCleared: true,
    },
    personality: 'Extremely intelligent, highly alert, focused. Workaholic mentality.',
    specialNotes: 'Seizure alert dog. May need to lie on handler during episodes. Bring mat for floor work.',
    hypoallergenicRating: 'low',
    serviceDogId: 'SD-2024-009',
    favoriteActivities: ['Herding', 'Frisbee', 'Problem-solving Games'],
    dietaryRestrictions: ['Sensitive stomach - limited ingredients'],
    knownAllergies: ['Beef'],
    emergencyContact: {
      name: 'Robert Thompson',
      phone: '+1-555-012-9999',
      relationship: 'Brother',
    },
    createdAt: new Date('2024-06-30'),
    updatedAt: new Date('2024-11-11'),
  },
  
  // Mobility Assistance Dogs
  {
    id: 'dog-003',
    userId: 'user-003',
    name: 'Bella',
    breed: 'German Shepherd',
    dateOfBirth: new Date('2018-09-20'),
    age: 6,
    weight: 75,
    weightUnit: 'lbs',
    sex: 'Female',
    color: 'Black & Tan',
    photo: 'https://images.unsplash.com/photo-1568572933382-74d440642117',
    microchip: 'MC-234567890',
    isServiceDog: true,
    taskType: 'mobility',
    taskDescription: 'Trained for mobility assistance including balance support, retrieving items, opening doors, helping with transfers, and light wheelchair pulling.',
    trainingCertification: '/docs/bella-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/michael-torres-signature.png',
    verificationStatus: 'green',
    checkmarkStatus: 'green',
    verificationDate: new Date('2024-03-05'),
    verifiedBy: 'Dr. James Wilson, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: false,
      publicAccessCleared: true,
    },
    personality: 'Loyal, protective, extremely patient. Gentle with handler.',
    specialNotes: 'Requires extra space on flights due to mobility harness. Wears working vest at all times.',
    hypoallergenicRating: 'low',
    serviceDogId: 'SD-2024-003',
    favoriteActivities: ['Light Jogging', 'Retrieve Games', 'Training Sessions'],
    dietaryRestrictions: ['Joint support supplements'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Carmen Torres',
      phone: '+1-555-345-9999',
      relationship: 'Mother',
    },
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-11-12'),
  },
  {
    id: 'dog-007',
    userId: 'user-007',
    name: 'Zeus',
    breed: 'Great Dane',
    dateOfBirth: new Date('2020-02-14'),
    age: 4,
    weight: 145,
    weightUnit: 'lbs',
    sex: 'Male',
    color: 'Harlequin',
    photo: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb',
    microchip: 'MC-678901234',
    isServiceDog: true,
    taskType: 'mobility',
    taskDescription: 'Trained for mobility support, balance, counterbalance work, and item retrieval for handler with muscular dystrophy. Certified for brace work.',
    trainingCertification: '/docs/zeus-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/chris-anderson-signature.png',
    verificationStatus: 'green',
    checkmarkStatus: 'green',
    verificationDate: new Date('2024-02-28'),
    verifiedBy: 'Dr. Sarah Mitchell, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: false,
      publicAccessCleared: true,
    },
    personality: 'Gentle giant, very calm, patient. Loves people.',
    specialNotes: 'Requires bulkhead seating on ALL flights due to size. Special harness required. Bring large water bowl.',
    hypoallergenicRating: 'low',
    serviceDogId: 'SD-2024-006',
    favoriteActivities: ['Slow Walks', 'Napping', 'Leaning on Handler'],
    dietaryRestrictions: ['Large breed formula', 'Glucosamine for joints'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Beth Anderson',
      phone: '+1-555-789-9999',
      relationship: 'Sister',
    },
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-11-14'),
  },
  
  // Hearing Alert Dogs
  {
    id: 'dog-004',
    userId: 'user-004',
    name: 'Charlie',
    breed: 'Labradoodle',
    dateOfBirth: new Date('2021-01-08'),
    age: 3,
    weight: 55,
    weightUnit: 'lbs',
    sex: 'Neutered',
    color: 'Apricot',
    photo: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8',
    microchip: 'MC-345678901',
    isServiceDog: true,
    taskType: 'hearing',
    taskDescription: 'Trained to alert handler to important sounds including doorbells, fire alarms, phone calls, approaching vehicles, crying babies, and name calls.',
    trainingCertification: '/docs/charlie-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/emily-chen-signature.png',
    verificationStatus: 'yellow',
    checkmarkStatus: 'yellow',
    verificationDate: new Date('2024-10-01'),
    verifiedBy: null,
    badges: {
      adaCompliant: true,
      tsaApproved: false,
      vetVerified: false,
      hypoallergenic: true,
      publicAccessCleared: true,
    },
    personality: 'Alert, friendly, quick to respond. Very social with other dogs.',
    specialNotes: 'Uses vibrating collar for alerts. Needs minimal grooming before flights. Bring grooming tools.',
    hypoallergenicRating: 'high',
    serviceDogId: 'SD-2024-004',
    favoriteActivities: ['Playing', 'Swimming', 'Meeting New People'],
    dietaryRestrictions: [],
    knownAllergies: [],
    emergencyContact: {
      name: 'David Chen',
      phone: '+1-555-456-9999',
      relationship: 'Husband',
    },
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-11-10'),
  },
  
  // Guide Dogs (Vision)
  {
    id: 'dog-009',
    userId: 'user-008',
    name: 'Buddy',
    breed: 'Goldendoodle',
    dateOfBirth: new Date('2019-08-25'),
    age: 5,
    weight: 62,
    weightUnit: 'lbs',
    sex: 'Neutered',
    color: 'Cream',
    photo: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e',
    microchip: 'MC-890123456',
    isServiceDog: true,
    taskType: 'vision',
    taskDescription: 'Trained as guide dog for visually impaired handler. Navigation, obstacle avoidance, intelligent disobedience, traffic checking.',
    trainingCertification: '/docs/buddy-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/ryan-williams-signature.png',
    verificationStatus: 'blue',
    checkmarkStatus: 'blue',
    verificationDate: new Date('2024-06-10'),
    verifiedBy: 'Dr. Rachel Kim, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: true,
      publicAccessCleared: true,
    },
    personality: 'Focused, intelligent, calm in all environments. Ignores distractions.',
    specialNotes: 'Guide dog. Wears special harness. Pre-board on flights. Never pet while working.',
    hypoallergenicRating: 'high',
    serviceDogId: 'SD-2024-008',
    favoriteActivities: ['Guiding', 'Relaxing at Home', 'Quiet Walks'],
    dietaryRestrictions: [],
    knownAllergies: [],
    emergencyContact: {
      name: 'Kelly Williams',
      phone: '+1-555-901-9999',
      relationship: 'Wife',
    },
    createdAt: new Date('2024-05-18'),
    updatedAt: new Date('2024-11-17'),
  },
  
  // Regular Pets (Free Tier)
  {
    id: 'dog-006',
    userId: 'user-010',
    name: 'Daisy',
    breed: 'Beagle',
    dateOfBirth: new Date('2018-07-22'),
    age: 6,
    weight: 25,
    weightUnit: 'lbs',
    sex: 'Spayed',
    color: 'Tri-color',
    photo: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530',
    microchip: 'MC-567890123',
    isServiceDog: false,
    taskType: null,
    taskDescription: null,
    trainingCertification: null,
    handlerAttestation: false,
    handlerSignature: null,
    verificationStatus: 'pending',
    checkmarkStatus: 'none',
    verificationDate: null,
    verifiedBy: null,
    badges: {
      adaCompliant: false,
      tsaApproved: false,
      vetVerified: false,
      hypoallergenic: false,
      publicAccessCleared: false,
    },
    personality: 'Friendly, curious, loves food. Howls when excited.',
    specialNotes: 'Regular pet, not a service dog. Great with kids. Food motivated.',
    hypoallergenicRating: 'low',
    serviceDogId: null,
    favoriteActivities: ['Sniffing', 'Eating', 'Napping'],
    dietaryRestrictions: ['Weight management formula'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Carlos Martinez',
      phone: '+1-555-678-9999',
      relationship: 'Husband',
    },
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-11-05'),
  },
  {
    id: 'dog-011',
    userId: 'user-011',
    name: 'Tucker',
    breed: 'Mixed Breed',
    dateOfBirth: new Date('2022-04-10'),
    age: 2,
    weight: 35,
    weightUnit: 'lbs',
    sex: 'Male',
    color: 'Brown & White',
    photo: 'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48',
    microchip: 'MC-112233445',
    isServiceDog: false,
    taskType: null,
    taskDescription: null,
    trainingCertification: null,
    handlerAttestation: false,
    handlerSignature: null,
    verificationStatus: 'pending',
    checkmarkStatus: 'none',
    verificationDate: null,
    verifiedBy: null,
    badges: {
      adaCompliant: false,
      tsaApproved: false,
      vetVerified: false,
      hypoallergenic: false,
      publicAccessCleared: false,
    },
    personality: 'Playful, energetic, loves everyone.',
    specialNotes: 'Adopted rescue dog. Still working on basic training.',
    hypoallergenicRating: 'low',
    serviceDogId: null,
    favoriteActivities: ['Playing Fetch', 'Running', 'Chewing Toys'],
    dietaryRestrictions: [],
    knownAllergies: [],
    emergencyContact: {
      name: 'Kevin Nguyen Sr.',
      phone: '+1-555-234-9999',
      relationship: 'Father',
    },
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-11-12'),
  },
  {
    id: 'dog-012',
    userId: 'user-012',
    name: 'Pepper',
    breed: 'Chihuahua',
    dateOfBirth: new Date('2020-09-14'),
    age: 4,
    weight: 6,
    weightUnit: 'lbs',
    sex: 'Female',
    color: 'Black',
    photo: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b',
    microchip: 'MC-998877665',
    isServiceDog: false,
    taskType: null,
    taskDescription: null,
    trainingCertification: null,
    handlerAttestation: false,
    handlerSignature: null,
    verificationStatus: 'pending',
    checkmarkStatus: 'none',
    verificationDate: null,
    verifiedBy: null,
    badges: {
      adaCompliant: false,
      tsaApproved: false,
      vetVerified: false,
      hypoallergenic: false,
      publicAccessCleared: false,
    },
    personality: 'Sassy, loyal to owner, suspicious of strangers.',
    specialNotes: 'Tiny dog. Needs sweater in cold weather. Scared of loud noises.',
    hypoallergenicRating: 'low',
    serviceDogId: null,
    favoriteActivities: ['Cuddling', 'Barking at Doorbell', 'Sunbathing'],
    dietaryRestrictions: ['Small breed formula'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Min-ji Kim',
      phone: '+1-555-345-9999',
      relationship: 'Roommate',
    },
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-15'),
  },
  
  // Additional Service Dogs (Diverse Breeds)
  {
    id: 'dog-013',
    userId: 'user-016',
    name: 'Atlas',
    breed: 'Rottweiler',
    dateOfBirth: new Date('2019-05-20'),
    age: 5,
    weight: 110,
    weightUnit: 'lbs',
    sex: 'Male',
    color: 'Black & Mahogany',
    photo: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379',
    microchip: 'MC-665544332',
    isServiceDog: true,
    taskType: 'mobility',
    taskDescription: 'Trained for balance support, counterbalance, forward momentum pull, and retrieval tasks. Certified for heavy-duty mobility work.',
    trainingCertification: '/docs/atlas-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/marcus-washington-signature.png',
    verificationStatus: 'green',
    checkmarkStatus: 'green',
    verificationDate: new Date('2024-05-15'),
    verifiedBy: 'Dr. James Wilson, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: false,
      publicAccessCleared: true,
    },
    personality: 'Steady, confident, extremely reliable. Protective instincts.',
    specialNotes: 'Large breed. Needs extra legroom on flights. Bring heavy-duty leash.',
    hypoallergenicRating: 'low',
    serviceDogId: 'SD-2024-010',
    favoriteActivities: ['Working', 'Swimming', 'Lounging'],
    dietaryRestrictions: ['Large breed formula', 'Joint supplements'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Tasha Washington',
      phone: '+1-555-456-9999',
      relationship: 'Wife',
    },
    createdAt: new Date('2024-04-22'),
    updatedAt: new Date('2024-11-13'),
  },
  {
    id: 'dog-014',
    userId: 'user-017',
    name: 'Rosie',
    breed: 'Australian Shepherd',
    dateOfBirth: new Date('2021-02-28'),
    age: 3,
    weight: 50,
    weightUnit: 'lbs',
    sex: 'Spayed',
    color: 'Blue Merle',
    photo: 'https://images.unsplash.com/photo-1505491680811-5a7daeafb7dc',
    microchip: 'MC-112244668',
    isServiceDog: true,
    taskType: 'medical-alert',
    taskDescription: 'Trained to detect migraine onset 30-45 minutes in advance. Alerts handler to take medication and find safe location.',
    trainingCertification: '/docs/rosie-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/natalie-rodriguez-signature.png',
    verificationStatus: 'blue',
    checkmarkStatus: 'blue',
    verificationDate: new Date('2024-08-10'),
    verifiedBy: 'Dr. Maria Garcia, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: false,
      publicAccessCleared: true,
    },
    personality: 'Energetic, intelligent, eager to please. Herding instincts.',
    specialNotes: 'Needs mental stimulation. Bring puzzle toys for flights. High energy.',
    hypoallergenicRating: 'low',
    serviceDogId: 'SD-2024-011',
    favoriteActivities: ['Herding', 'Frisbee', 'Agility'],
    dietaryRestrictions: ['Active dog formula'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Miguel Rodriguez',
      phone: '+1-555-567-9999',
      relationship: 'Husband',
    },
    createdAt: new Date('2023-07-15'),
    updatedAt: new Date('2024-11-14'),
  },
  {
    id: 'dog-015',
    userId: 'user-019',
    name: 'Diesel',
    breed: 'Doberman Pinscher',
    dateOfBirth: new Date('2020-11-12'),
    age: 4,
    weight: 85,
    weightUnit: 'lbs',
    sex: 'Male',
    color: 'Black & Rust',
    photo: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95',
    microchip: 'MC-556677889',
    isServiceDog: true,
    taskType: 'ptsd',
    taskDescription: 'Trained for PTSD support including space creation, alert behaviors, grounding techniques, and nightmare interruption.',
    trainingCertification: '/docs/diesel-training-cert.pdf',
    handlerAttestation: true,
    handlerSignature: '/signatures/isabella-garcia-signature.png',
    verificationStatus: 'green',
    checkmarkStatus: 'green',
    verificationDate: new Date('2024-09-05'),
    verifiedBy: 'Dr. Sarah Mitchell, DVM',
    badges: {
      adaCompliant: true,
      tsaApproved: true,
      vetVerified: true,
      hypoallergenic: false,
      publicAccessCleared: true,
    },
    personality: 'Loyal, alert, confident. Very attuned to handler.',
    specialNotes: 'Looks intimidating but is gentle. People may be nervous around him.',
    hypoallergenicRating: 'low',
    serviceDogId: 'SD-2024-012',
    favoriteActivities: ['Jogging', 'Training', 'Guarding'],
    dietaryRestrictions: ['High-protein formula'],
    knownAllergies: [],
    emergencyContact: {
      name: 'Rosa Garcia',
      phone: '+1-555-789-9999',
      relationship: 'Mother',
    },
    createdAt: new Date('2024-08-18'),
    updatedAt: new Date('2024-11-16'),
  },
];

// Helper functions
export function getDogById(id: string): Dog | undefined {
  return mockDogs.find(dog => dog.id === id);
}

export function getDogsByUserId(userId: string): Dog[] {
  return mockDogs.filter(dog => dog.userId === userId);
}

export function getServiceDogs(): Dog[] {
  return mockDogs.filter(dog => dog.isServiceDog);
}

export function getDogsByVerificationStatus(status: string): Dog[] {
  return mockDogs.filter(dog => dog.verificationStatus === status);
}

