// Dog Passport: Mock Users Data
// From final-mock-data.md specification

import { User } from '../types';

export const mockUsers: User[] = [
  // Premium Blue Tier Users (High Engagement)
  {
    id: 'user-001',
    email: 'john.doe@gmail.com',
    name: 'John Doe',
    phone: '+1-555-123-4567',
    avatar: 'https://i.pravatar.cc/150?img=12',
    subscriptionTier: 'blue',
    subscriptionExpiresAt: new Date('2026-12-31'),
    createdAt: new Date('2023-01-15'),
    location: 'Portland, OR',
    timezone: 'America/Los_Angeles',
    preferences: {
      notifications: { push: true, email: true, sms: false },
      theme: 'auto',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 2,
      recordsUploaded: 24,
      communityPosts: 12,
      travelBookings: 8,
    },
  },
  {
    id: 'user-002',
    email: 'sarah.johnson@yahoo.com',
    name: 'Sarah Johnson',
    phone: '+1-555-234-5678',
    avatar: 'https://i.pravatar.cc/150?img=47',
    subscriptionTier: 'blue',
    subscriptionExpiresAt: new Date('2026-06-15'),
    createdAt: new Date('2023-03-10'),
    location: 'San Francisco, CA',
    timezone: 'America/Los_Angeles',
    preferences: {
      notifications: { push: true, email: true, sms: true },
      theme: 'light',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 18,
      communityPosts: 24,
      travelBookings: 15,
    },
  },
  {
    id: 'user-003',
    email: 'michael.torres@outlook.com',
    name: 'Michael Torres',
    phone: '+1-555-345-6789',
    avatar: 'https://i.pravatar.cc/150?img=33',
    subscriptionTier: 'blue',
    subscriptionExpiresAt: new Date('2026-03-20'),
    createdAt: new Date('2023-02-20'),
    location: 'Austin, TX',
    timezone: 'America/Chicago',
    preferences: {
      notifications: { push: true, email: false, sms: false },
      theme: 'dark',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 15,
      communityPosts: 8,
      travelBookings: 6,
    },
  },
  
  // Premium Tier Users
  {
    id: 'user-004',
    email: 'emily.chen@gmail.com',
    name: 'Emily Chen',
    phone: '+1-555-456-7890',
    avatar: 'https://i.pravatar.cc/150?img=27',
    subscriptionTier: 'premium',
    subscriptionExpiresAt: new Date('2025-11-01'),
    createdAt: new Date('2023-11-05'),
    location: 'Seattle, WA',
    timezone: 'America/Los_Angeles',
    preferences: {
      notifications: { push: true, email: true, sms: false },
      theme: 'auto',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 3,
      recordsUploaded: 32,
      communityPosts: 6,
      travelBookings: 4,
    },
  },
  {
    id: 'user-005',
    email: 'david.park@icloud.com',
    name: 'David Park',
    phone: '+1-555-567-8901',
    avatar: 'https://i.pravatar.cc/150?img=15',
    subscriptionTier: 'premium',
    subscriptionExpiresAt: new Date('2025-09-30'),
    createdAt: new Date('2024-01-12'),
    location: 'New York, NY',
    timezone: 'America/New_York',
    preferences: {
      notifications: { push: true, email: true, sms: true },
      theme: 'light',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 12,
      communityPosts: 14,
      travelBookings: 10,
    },
  },
  {
    id: 'user-006',
    email: 'amanda.lewis@gmail.com',
    name: 'Amanda Lewis',
    phone: '+1-555-890-1234',
    avatar: 'https://i.pravatar.cc/150?img=44',
    subscriptionTier: 'premium',
    subscriptionExpiresAt: new Date('2025-08-28'),
    createdAt: new Date('2023-12-10'),
    location: 'Chicago, IL',
    timezone: 'America/Chicago',
    preferences: {
      notifications: { push: true, email: false, sms: false },
      theme: 'dark',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 10,
      communityPosts: 18,
      travelBookings: 7,
    },
  },
  {
    id: 'user-007',
    email: 'chris.anderson@yahoo.com',
    name: 'Chris Anderson',
    phone: '+1-555-789-0123',
    avatar: 'https://i.pravatar.cc/150?img=18',
    subscriptionTier: 'premium',
    subscriptionExpiresAt: new Date('2025-07-15'),
    createdAt: new Date('2024-01-25'),
    location: 'Boston, MA',
    timezone: 'America/New_York',
    preferences: {
      notifications: { push: false, email: true, sms: false },
      theme: 'auto',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 8,
      communityPosts: 3,
      travelBookings: 2,
    },
  },
  
  // Family Tier Users (Multiple Dogs)
  {
    id: 'user-008',
    email: 'ryan.williams@outlook.com',
    name: 'Ryan Williams',
    phone: '+1-555-901-2345',
    avatar: 'https://i.pravatar.cc/150?img=51',
    subscriptionTier: 'family',
    subscriptionExpiresAt: new Date('2025-12-10'),
    createdAt: new Date('2024-05-18'),
    location: 'Miami, FL',
    timezone: 'America/New_York',
    preferences: {
      notifications: { push: true, email: true, sms: false },
      theme: 'light',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 4,
      recordsUploaded: 45,
      communityPosts: 9,
      travelBookings: 5,
    },
  },
  {
    id: 'user-009',
    email: 'lisa.thompson@icloud.com',
    name: 'Lisa Thompson',
    phone: '+1-555-012-3456',
    avatar: 'https://i.pravatar.cc/150?img=29',
    subscriptionTier: 'family',
    subscriptionExpiresAt: new Date('2026-01-22'),
    createdAt: new Date('2024-06-30'),
    location: 'Phoenix, AZ',
    timezone: 'America/Phoenix',
    preferences: {
      notifications: { push: true, email: true, sms: true },
      theme: 'auto',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 3,
      recordsUploaded: 38,
      communityPosts: 11,
      travelBookings: 12,
    },
  },
  
  // Free Tier Users (Limited Features)
  {
    id: 'user-010',
    email: 'jessica.martinez@gmail.com',
    name: 'Jessica Martinez',
    phone: '+1-555-678-9012',
    avatar: 'https://i.pravatar.cc/150?img=32',
    subscriptionTier: 'free',
    subscriptionExpiresAt: null,
    createdAt: new Date('2024-09-01'),
    location: 'Denver, CO',
    timezone: 'America/Denver',
    preferences: {
      notifications: { push: true, email: false, sms: false },
      theme: 'light',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 3,
      communityPosts: 1,
      travelBookings: 0,
    },
  },
  {
    id: 'user-011',
    email: 'kevin.nguyen@yahoo.com',
    name: 'Kevin Nguyen',
    phone: '+1-555-234-9876',
    avatar: 'https://i.pravatar.cc/150?img=60',
    subscriptionTier: 'free',
    subscriptionExpiresAt: null,
    createdAt: new Date('2024-10-15'),
    location: 'San Diego, CA',
    timezone: 'America/Los_Angeles',
    preferences: {
      notifications: { push: false, email: true, sms: false },
      theme: 'auto',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 2,
      communityPosts: 0,
      travelBookings: 0,
    },
  },
  {
    id: 'user-012',
    email: 'rachel.kim@gmail.com',
    name: 'Rachel Kim',
    phone: '+1-555-345-1234',
    avatar: 'https://i.pravatar.cc/150?img=48',
    subscriptionTier: 'free',
    subscriptionExpiresAt: null,
    createdAt: new Date('2024-11-01'),
    location: 'Atlanta, GA',
    timezone: 'America/New_York',
    preferences: {
      notifications: { push: true, email: true, sms: false },
      theme: 'dark',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 1,
      communityPosts: 0,
      travelBookings: 0,
    },
  },
  
  // International Users
  {
    id: 'user-013',
    email: 'oliver.smith@gmail.com',
    name: 'Oliver Smith',
    phone: '+44-20-7946-0958',
    avatar: 'https://i.pravatar.cc/150?img=58',
    subscriptionTier: 'premium',
    subscriptionExpiresAt: new Date('2025-10-10'),
    createdAt: new Date('2024-02-14'),
    location: 'London, UK',
    timezone: 'Europe/London',
    preferences: {
      notifications: { push: true, email: true, sms: false },
      theme: 'light',
      language: 'en-GB',
      units: 'metric',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 9,
      communityPosts: 5,
      travelBookings: 3,
    },
  },
  {
    id: 'user-014',
    email: 'sophia.dupont@gmail.com',
    name: 'Sophia Dupont',
    phone: '+33-1-42-86-82-00',
    avatar: 'https://i.pravatar.cc/150?img=43',
    subscriptionTier: 'blue',
    subscriptionExpiresAt: new Date('2026-05-05'),
    createdAt: new Date('2023-08-20'),
    location: 'Paris, France',
    timezone: 'Europe/Paris',
    preferences: {
      notifications: { push: true, email: true, sms: true },
      theme: 'auto',
      language: 'fr',
      units: 'metric',
    },
    stats: {
      dogsManaged: 2,
      recordsUploaded: 20,
      communityPosts: 16,
      travelBookings: 18,
    },
  },
  {
    id: 'user-015',
    email: 'liam.murphy@icloud.com',
    name: 'Liam Murphy',
    phone: '+61-2-9374-4000',
    avatar: 'https://i.pravatar.cc/150?img=56',
    subscriptionTier: 'premium',
    subscriptionExpiresAt: new Date('2025-12-20'),
    createdAt: new Date('2024-03-08'),
    location: 'Sydney, Australia',
    timezone: 'Australia/Sydney',
    preferences: {
      notifications: { push: true, email: false, sms: false },
      theme: 'dark',
      language: 'en-AU',
      units: 'metric',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 11,
      communityPosts: 7,
      travelBookings: 4,
    },
  },
  
  // Additional US Users (Diverse Cities)
  {
    id: 'user-016',
    email: 'marcus.washington@gmail.com',
    name: 'Marcus Washington',
    phone: '+1-555-456-7891',
    avatar: 'https://i.pravatar.cc/150?img=14',
    subscriptionTier: 'premium',
    subscriptionExpiresAt: new Date('2025-11-15'),
    createdAt: new Date('2024-04-22'),
    location: 'Detroit, MI',
    timezone: 'America/Detroit',
    preferences: {
      notifications: { push: true, email: true, sms: false },
      theme: 'auto',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 7,
      communityPosts: 4,
      travelBookings: 2,
    },
  },
  {
    id: 'user-017',
    email: 'natalie.rodriguez@yahoo.com',
    name: 'Natalie Rodriguez',
    phone: '+1-555-567-8902',
    avatar: 'https://i.pravatar.cc/150?img=45',
    subscriptionTier: 'blue',
    subscriptionExpiresAt: new Date('2026-04-10'),
    createdAt: new Date('2023-07-15'),
    location: 'Houston, TX',
    timezone: 'America/Chicago',
    preferences: {
      notifications: { push: true, email: true, sms: true },
      theme: 'light',
      language: 'es',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 2,
      recordsUploaded: 22,
      communityPosts: 19,
      travelBookings: 11,
    },
  },
  {
    id: 'user-018',
    email: 'daniel.patel@outlook.com',
    name: 'Daniel Patel',
    phone: '+1-555-678-9013',
    avatar: 'https://i.pravatar.cc/150?img=68',
    subscriptionTier: 'family',
    subscriptionExpiresAt: new Date('2025-09-05'),
    createdAt: new Date('2024-07-10'),
    location: 'Philadelphia, PA',
    timezone: 'America/New_York',
    preferences: {
      notifications: { push: true, email: false, sms: false },
      theme: 'dark',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 3,
      recordsUploaded: 28,
      communityPosts: 8,
      travelBookings: 6,
    },
  },
  {
    id: 'user-019',
    email: 'isabella.garcia@gmail.com',
    name: 'Isabella Garcia',
    phone: '+1-555-789-0124',
    avatar: 'https://i.pravatar.cc/150?img=49',
    subscriptionTier: 'premium',
    subscriptionExpiresAt: new Date('2025-10-30'),
    createdAt: new Date('2024-08-18'),
    location: 'Dallas, TX',
    timezone: 'America/Chicago',
    preferences: {
      notifications: { push: true, email: true, sms: false },
      theme: 'auto',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 9,
      communityPosts: 6,
      travelBookings: 3,
    },
  },
  {
    id: 'user-020',
    email: 'ethan.lee@icloud.com',
    name: 'Ethan Lee',
    phone: '+1-555-890-1235',
    avatar: 'https://i.pravatar.cc/150?img=69',
    subscriptionTier: 'free',
    subscriptionExpiresAt: null,
    createdAt: new Date('2024-11-10'),
    location: 'San Jose, CA',
    timezone: 'America/Los_Angeles',
    preferences: {
      notifications: { push: false, email: true, sms: false },
      theme: 'light',
      language: 'en',
      units: 'imperial',
    },
    stats: {
      dogsManaged: 1,
      recordsUploaded: 1,
      communityPosts: 0,
      travelBookings: 0,
    },
  },
];

// Helper function to get user by ID
export function getUserById(id: string): User | undefined {
  return mockUsers.find(user => user.id === id);
}

// Helper function to get current user (for demo purposes, using first user)
export function getCurrentUser(): User {
  return mockUsers[0];
}

